<?php

/**
 * Implementation of hook_feeds_plugins().
 */
function feeds_xpathparser_feeds_plugins() {
  $path = drupal_get_path('module', 'feeds_xpathparser');
  return array(
    'FeedsXPathParserBase' => array(
      'hidden' => TRUE,
      'handler' => array(
        'parent' => 'FeedsParser',
        'class'  => 'FeedsXPathParserBase',
        'file'   => 'FeedsXPathParserBase.inc',
        'path'   => $path,
      ),
    ),
    'FeedsXPathParserHTML' => array(
      'name' => t('XPath HTML parser'),
      'description' => t('Parse HTML using XPath.'),
      'handler' => array(
        'parent' => 'FeedsXPathParserBase',
        'class'  => 'FeedsXPathParserHTML',
        'file'   => 'FeedsXPathParserHTML.inc',
        'path'   => $path,
      ),
    ),
    'FeedsXPathParserXML' => array(
      'name' => t('XPath XML parser'),
      'description' => t('Parse XML using XPath.'),
      'handler' => array(
        'parent' => 'FeedsXPathParserBase',
        'class'  => 'FeedsXPathParserXML',
        'file'   => 'FeedsXPathParserXML.inc',
        'path'   => $path,
      ),
    ),
  );
}
