<?php
// $Id: parser_kml.module,v 1.1.2.1.2.1 2011/02/09 18:26:57 jcnventura Exp $

/**
 * @file
 * Parse the incoming URL with SimpleXML into a FeedAPI compatible data structure.
 */

/**
 * Implementation of hook_feeds_plugins().
 */
function parser_kml_feeds_plugins() {
  $path = drupal_get_path('module', 'parser_kml');
  $info = array();

   $info['FeedsParserKML'] = array(
    'name'        => t('KML parser'),
    'description' => t('Parse KML.'),
    'handler'     => array(
      'parent' => 'FeedsParser',
      'class'  => 'FeedsParserKML',
      'file'   => 'FeedsParserKML.inc',
      'path'   => $path,
    ),
  );

  return $info;
}

/**
 * Implementation of hook_enable().
 *
 * Clear Feed's plugin cache so that this plugin shows up.
 */
function parser_kml_enable() {
  cache_clear_all('plugins:feeds:plugins', 'cache');
}
